#!/bin/sh

echo "**Performing pre-commit actions**"

echo "**Formatting code with spotless**"
./gradlew spotlessApply

echo "**Adding changes from reformat**"
# Add changes for any files already added to the repo - will not support partial repo commits currently
git add -u

status=$?

echo "**Done with pre-commit**"

exit $status
