#!/bin/sh

echo "**Performing pre-commit actions**"

echo "- Formatting code with spotless"
./gradlew spotlessApply

echo "- Adding any changes from reformat"
# Add changes for any files already staged
git update-index --again

status=$?

echo "**Done with pre-commit**"

exit $status
